version: '3.8'

services:
  app:
    build: .
    container_name: google-docs-highlighter
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge